# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: 아니 근데 오늘 진짜
description: "AI 대화형 일기 서비스"
url: https://github.com/kookmin-sw/capstone-2024-13
baseurl: ""

author:
    name: "kookmin-sw/capstone-13"
    url: https://github.com/kookmin-sw/capstone-2024-13

# Custom vars
version: 1.0.0

github:
    repo: https://github.com/kookmin-sw/capstone-2024-13
