# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: true

# Setup
title: 아니 근데 오늘 진짜
description: "AI 대화형 일기 서비스"
url: https://github.com/kookmin-sw/capstone-2024-13
baseurl: /docs

author:
    name: "Kookmin-SW/Capstone-13"
    url: https://github.com/kookmin-sw/capstone-2024-13

paginate: 5

# Custom vars
version: 1.0.0

github:
    repo: https://github.com/kookmin-sw/capstone-2024-13
